blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"

urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail')
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from django_portfolio import settings
from blog import urls
from django.conf.urls.static import static

from portfolio import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime

class Post(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField()
    description = models.TextField()
    date = models.DateField(default=datetime.date.today)
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

class PostImage(models.Model):
    post = models.ForeignKey(Post, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='blog/images')

    def __str__(self):
        return f"Image for {self.post.title}"

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)
    

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post

def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {'posts': posts})

def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request, 'home.html', {'projects': projects})
    

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}

<div class="text-center">
    <h1>Proyecto</h1>

    <h2>{{ post.title }}</h2>
    <a href="{{ post.url }}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{ post.url }}</a>

    <div class="my-4">
        <p>{{ post.description|safe }}</p>
    </div>

    <div class="row">
        {% for image in post.images.all %}
            <div class="col-md-4 col-sm-6 mb-4">
                <div class="card h-100">
                    <div class="image-container">
                        <img src="{{ image.image.url }}" alt="{{ post.title }}" class="card-img-top">
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}


<h1>Proyectos</h1>


{% for post in posts %}
<div class="pd-3">
    <div class="card card-body bg-black">
        <div class="row">
            <div class="col-3">
                <img src="{{post.image.url}}" alt="{{post.title}}" class="img-fluid">
            </div>
            
            <div class="col-9">
                <h2>{{post.title}}</h2>
                <p>{{post.description|striptags| truncatechars:100}}</p>
                <p>{{post.date|date:'M d Y'|upper}}</p>
                <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">{{post.title}}</a>
            </div>
        </div>
    </div>
</div>
{% endfor %}


{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %} {% block content %} {% load static %}

<header class="row bg-black">
  <div class="col-md-4">
    <img src="{% static 'portfolio/profile.jpg' %}" alt="" class="img-fluid"> 
  </div>
  <div class="col-md-8 my-auto">
    <h1>Soy <strong> Alex Hernandez Rios</strong></h1>
    <h3>Soy desarolloador Python Full stack</h3>
    <p>
      Soy una persona proactiva, excelente compañero de equipo, organizado y responsable. Disfruto
      mucho aprender cosas nuevas, por lo que mi objetivo es un puesto desafiante y dinámico donde
      poder compartir mi experiencia y a su vez sumar nuevos conocimientos. Especializado en el
      desarrollo de aplicaciones móviles y sitios web, estoy comprometido con la eficiencia y la calidad
      en cada proyecto.
    </p>
    <a href="{% static 'portfolio/document.pdf' %}" class="btn btn-primary btn-lg rounded-0 my-3">Descargar CV</a>
  </div>
</header>

<div class="row my-4 text-center">
  <h3>Mis proyectos</h3>
  <p>
    Aqui esta link a algunos de mis proyectos de desarollo
  </p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img src="{{project.image.url}}" alt="{{project.title}}" class="card-img-top" />
      <div class="card-body text-light">
        <h2>{{project.title}}</h2>
        <p>{{project.description}}</p>
        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="_blank">{{project.url}}</a>
        {% endif %}
      </div>
    </div>
  </div>

  {% endfor %} {% endblock %}
</div>

portfolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django Portfoliot</title>
    <link rel="stylesheet" href="">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">

</head>
<body class="text-light">


    {% include 'partials/navbar.html' %}

    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>
        
  
    

</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">Alex Hernandez</a>

      <!-- Enlaces de navegación y botón alineados horizontalmente -->
      <div class="navbar-nav ms-auto d-flex align-items-center">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:posts' %}">Portafolio Git</a>
          <a class="btn btn-primary btn-sm ms-2" href="{% static 'portfolio/document.pdf' %}" target="_blank">Descargar CV</a>
      </div>
  </div>
</nav>